[theme]
base = "light"
primaryColor = "#6B7280"                    # Soft slate grey (calm, professional, insight-driven)
backgroundColor = "#F3F4F6"                 # Warm off-white (gentle, inviting like a blooming 🌸)
secondaryBackgroundColor = "#FFFFFF"        # Pure white for cards (clean, focused)
textColor = "#1F2937"                       # Deep slate (readable, authoritative yet warm)
font = "Inter"                             # Modern, clean sans-serif with excellent readability

[browser]
gatherUsageStats = false
