[theme]
base = "light"
primaryColor = "#5A67D8"                    # Calming violet-blue (trust + insight)
backgroundColor = "#F9FAFB"                 # Very soft grey-white
secondaryBackgroundColor = "#FFFFFF"        # Card backgrounds
textColor = "#111827"                       # Rich charcoal for readability
font = "sans serif"

[browser]
gatherUsageStats = false
